version: '3.9'
services:
  mysql:
    container_name: practice_db
    build: ./mysql
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=Asia/Tokyo
    restart: always
    tty: true
    stdin_open: true
    ports:
      - '33070:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev_docker
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  app:
    container_name: app
    build: ./rails
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspace
      - bundle_path:/bundle
    # secrets:
    #   - source: host_ssh_key
    #     mode: 0600
    environment:
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:6.2.5-alpine
    volumes:
      - "../.docker/redis/volums:/data"

  # db:
  #   build: ./postgres
  #   volumes:
  #     - "../.docker/postgresql/volums:/var/lib/postgresql"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   tty: true
volumes:
  bundle_path:
  dbdata:
    driver: local

# secrets:
#   host_ssh_key:
#     file: ~/.ssh/id_rsa
