default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  collation: utf8_general_ci
development:
  <<: *default
  database: dev_docker
  username: root
  password: password
  host: practice_db
